### PR TITLE
Display python venv

### PR DESCRIPTION
**Pull request by mrv96**
Display python virtual environment inside the theme

Additional minor changes:
- add empty line to space current command line from the previous one
- add two spaces between the theme and the command cursor

### CODE REVIEW

**Comment by mrv96** [comment]
I just added a comment to remove local functions to use the standard ones in mercurial and virtualenv plugins.

**Comment by igormp** [comment]
Thanks for the PR! 

Even though the use of the built-in functions is very welcome, I personally didn't like added empty lines and extra spacing before the cursor. Would you mind reverting those specific changes?

**Comment by mrv96** [comment]
Hi Igor, this theme is yours, I'll revert those changes.

I want to use this theme in my scripts, but I would also like to delete my fork after this PR. Can you accept this PR then I'll made another one to do the revert?

In this way I could point my scripts to a specific commit of your repo containing the spaces and extra lines that I'm going to revert.

**Comment by igormp** [comment]
Sure, sounds good to me :)

**Comment by mrv96** [comment]
Thank you very much. I've just performed the revert here: https://github.com/igormp/Imp/pull/8

**Comment by igormp** [comment]
Perfect, thank you!

**Pull request merged**
